# Generated by Django 4.1.5 on 2026-03-05 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiresList',
            fields=[
                ('inquire_id', models.BigAutoField(default=4999000000001, editable=False, primary_key=True, serialize=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=4999000010000, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=4999000020000, null=True)),
                ('inquire_type', models.JSONField(default=list)),
                ('your_questions', models.TextField(blank=True, null=True)),
                ('your_planned', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('discover_type', models.JSONField(default=list)),
                ('comments', models.TextField(blank=True, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2inquire', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2inquire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inquires_list',
                'ordering': ['-ss_created_on'],
            },
        ),
    ]
