# Generated by Django 4.1.5 on 2026-03-06 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inquire_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquireslist',
            name='inquire_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
