# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='in_exam_type',
            fields=[
                ('exam_type_id', models.BigAutoField(default=1255330000000, editable=False, primary_key=True, serialize=False)),
                ('exam_type_no', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=16631000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=177710000000, editable=False, null=True)),
            ],
        ),
    ]
