# Generated by Django 4.1.5 on 2025-05-07 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_exam_type',
            fields=[
                ('exam_type_id', models.BigAutoField(default=1255330000000, editable=False, primary_key=True, serialize=False)),
                ('exam_type_no', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=16631000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=177710000000, editable=False, null=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_exam_type', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_exam_type', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_exam_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
