# Generated by Django 4.1.5 on 2025-07-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_exam_type',
            name='is_half_yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_exam_type',
            name='is_yearly',
            field=models.BooleanField(default=False),
        ),
    ]
