# Generated by Django 4.1.5 on 2024-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_systemshutdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemshutdown',
            name='sys_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
