# Generated by Django 4.1.5 on 2026-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
