# Generated by Django 4.1.5 on 2024-11-05 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bill_templates', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_apps_templates',
            fields=[
                ('temp_id', models.BigAutoField(default=1099900000000, editable=False, primary_key=True, serialize=False)),
                ('btemp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('xxxtemp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1088400000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=107750000000, editable=False, null=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2bill_temp', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2bill_temp', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2bill_temp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='in_bill_templates',
        ),
    ]
