# Generated by Django 4.1.5 on 2024-11-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_templates', '0004_in_apps_templates_delete_in_bill_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_apps_templates',
            old_name='xxxtemp_name',
            new_name='due_coll_temp_name',
        ),
        migrations.AddField(
            model_name='in_apps_templates',
            name='inv_can_temp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_apps_templates',
            name='item_can_temp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='in_apps_templates',
            name='refund_coll_temp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
