# Generated by Django 4.1.5 on 2024-11-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_templates', '0005_rename_xxxtemp_name_in_apps_templates_due_coll_temp_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_apps_templates',
            old_name='btemp_name',
            new_name='billing_temp',
        ),
        migrations.RenameField(
            model_name='in_apps_templates',
            old_name='due_coll_temp_name',
            new_name='due_coll_temp',
        ),
        migrations.RenameField(
            model_name='in_apps_templates',
            old_name='inv_can_temp_name',
            new_name='inv_can_temp',
        ),
        migrations.RenameField(
            model_name='in_apps_templates',
            old_name='item_can_temp_name',
            new_name='item_can_temp',
        ),
        migrations.RenameField(
            model_name='in_apps_templates',
            old_name='refund_coll_temp_name',
            new_name='refund_coll_temp',
        ),
    ]
