# Generated by Django 4.1.5 on 2026-04-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('why_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
