# Generated by Django 4.1.5 on 2025-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_reconciliation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_reconciliationdtl',
            name='recon_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_reconciliationdtl',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
