# Generated by Django 4.1.5 on 2026-03-07 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollList',
            fields=[
                ('enroll_id', models.BigAutoField(default=1750000700001, editable=False, primary_key=True, serialize=False)),
                ('enroll_title', models.CharField(blank=True, max_length=150, null=True)),
                ('enroll_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_enroll_price', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_offer_price', models.BooleanField(default=False)),
                ('enroll_caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1750000800001, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1750000900001, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2enroll', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2enroll', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enroll_list',
                'ordering': ['-enroll_id'],
            },
        ),
        migrations.CreateModel(
            name='EnrollDetails',
            fields=[
                ('enrolldtls_id', models.BigAutoField(default=1678000600001, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('enroll_dtls', models.CharField(blank=True, max_length=2500, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1678000700001, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1678000800001, editable=False, null=True)),
                ('enroll_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enroll2enrolldtls', to='enroll_us.enrolllist')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2enrolldtls', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2enrolldtls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enroll_details',
                'ordering': ['-enrolldtls_id'],
            },
        ),
    ]
