# Generated by Django 4.1.5 on 2026-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolllist',
            name='is_most_popular',
            field=models.BooleanField(default=False),
        ),
    ]
