# Generated by Django 4.1.5 on 2026-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_us', '0002_enrolllist_is_most_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolldetails',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
