# Generated by Django 4.1.5 on 2026-04-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_us', '0003_enrolldetails_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollBookingDtls',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_bookings', to='enroll_us.enrolllist')),
            ],
            options={
                'db_table': 'enroll_booking_dtls',
            },
        ),
    ]
