# Generated by Django 4.1.5 on 2026-04-06 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll_us', '0004_enrollbookingdtls'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollbookingdtls',
            name='ss_created_session',
            field=models.BigIntegerField(blank=True, default=1678000900001, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='enrollbookingdtls',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2enrollbooking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollbookingdtls',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrollbookingdtls',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2enrollbooking', to=settings.AUTH_USER_MODEL),
        ),
    ]
