# Generated by Django 4.1.5 on 2026-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_us', '0005_enrollbookingdtls_ss_created_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollbookingdtls',
            name='course_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollbookingdtls',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
