# Generated by Django 4.1.5 on 2026-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll_us', '0006_enrollbookingdtls_course_amt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolllist',
            options={'ordering': ['order_by', '-enroll_id']},
        ),
        migrations.AddField(
            model_name='enrolllist',
            name='order_by',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
