# Generated by Django 4.1.5 on 2025-11-14 05:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('section_setup', '0002_initial'),
        ('registrations', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups_setup', '0003_initial'),
        ('class_setup', '0003_initial'),
        ('shift_setup', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_half_yearly_roll_sec_change_info',
            fields=[
                ('hyrscinfo_id', models.BigAutoField(default=1234900900001, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('hyrscinfo_year', models.IntegerField(default=2025, editable=False)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1468450900000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1257400506000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2hyrscinfo', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2hyrscinfo', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2hyrscinfo', to='groups_setup.in_groups')),
                ('is_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2hyrscinfo', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2hyrscinfo', to='organizations.organizationlst')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2hyrscinfo', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2hyrscinfo', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2hyrscinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='in_half_yearly_roll_sec_change_history',
            fields=[
                ('hyrschistory_id', models.BigAutoField(default=1479600000001, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('hyrscinfo_year', models.IntegerField(default=2025, editable=False)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('old_roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('new_roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=14700500300000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=10351076890000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2hyrsc_history', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2hyrsc_history', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2hyrsc_history', to='groups_setup.in_groups')),
                ('hyrscinfo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hyrscinfo_id2hyrsc_history', to='half_yearly_roll_sec_change.in_half_yearly_roll_sec_change_info')),
                ('new_section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_section_id2hyrsc_history', to='section_setup.in_section')),
                ('old_section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_section_id2hyrsc_history', to='section_setup.in_section')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2hyrsc_history', to='organizations.organizationlst')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2hyrsc_history', to='registrations.in_registrations')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2hyrsc_history', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2hyrsc_history', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2hyrsc_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
