# Generated by Django 4.1.5 on 2025-11-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('half_yearly_roll_sec_change', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_half_yearly_roll_sec_change_info',
            name='is_rollback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_half_yearly_roll_sec_change_info',
            name='is_rollback_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_rollback_id2hyrscinfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_half_yearly_roll_sec_change_info',
            name='is_rollback_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
