# Generated by Django 4.1.5 on 2025-11-16 06:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_setup', '0003_initial'),
        ('registrations', '0003_initial'),
        ('groups_setup', '0003_initial'),
        ('shift_setup', '0002_initial'),
        ('section_setup', '0002_initial'),
        ('organizations', '0002_initial'),
        ('half_yearly_roll_sec_change', '0003_in_half_yearly_roll_sec_change_info_is_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_half_yearly_rollsecchange_rollback_history',
            fields=[
                ('hyrscrollbackh_id', models.BigAutoField(default=1939400000001, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('hyrscinfo_year', models.IntegerField(default=2025, editable=False)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('new_roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('rollback_roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=14888900300000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=10588096810000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2hyrsc_rollback_history', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2hyrsc_rollback_history', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2hyrsc_rollback_history', to='groups_setup.in_groups')),
                ('hyrscinfo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hyrscinfo_id2hyrsc_rollback_history', to='half_yearly_roll_sec_change.in_half_yearly_roll_sec_change_info')),
                ('new_section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_section_id2hyrsc_rollback_history', to='section_setup.in_section')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2hyrsc_rollback_history', to='organizations.organizationlst')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2hyrsc_rollback_history', to='registrations.in_registrations')),
                ('rollback_section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rollback_section_id2hyrsc_rollback_history', to='section_setup.in_section')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2hyrsc_rollback_history', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2hyrsc_rollback_history', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2hyrsc_rollback_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
