# Generated by Django 4.1.5 on 2025-11-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merit_app_card_print', '0003_in_merit_position_approval_is_half_roll_sec_change_and_more'),
        ('half_yearly_roll_sec_change', '0004_in_half_yearly_rollsecchange_rollback_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_half_yearly_roll_sec_change_info',
            name='merit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merit_id2hyrscinfo', to='merit_app_card_print.in_merit_position_approval'),
        ),
    ]
