# Generated by Django 4.1.5 on 2025-03-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_R_N_with_without', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='without_grndtl',
            name='dis_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
