# Generated by Django 4.1.5 on 2025-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_R_N_with_without', '0004_without_grndtl_dis_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='without_grn',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='is_cash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='is_credit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='wo_grn_id',
            field=models.BigAutoField(db_index=True, default=1901010000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='without_grn',
            name='wo_grn_no',
            field=models.CharField(db_index=True, editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='without_grndtl',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='without_grndtl',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='without_grndtl',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='without_grndtl',
            name='wo_grn_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='without_grndtl',
            name='wo_grndtl_id',
            field=models.BigAutoField(db_index=True, default=100410000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='without_grn',
            index=models.Index(fields=['id_org', 'branch_id', 'supplier_id', 'transaction_date', 'store_id', 'is_cash', 'is_approved'], name='G_R_N_with__id_org__5e3cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='without_grn',
            index=models.Index(fields=['id_org', 'branch_id', 'supplier_id', 'transaction_date', 'store_id', 'is_credit', 'is_approved'], name='G_R_N_with__id_org__21c759_idx'),
        ),
        migrations.AddIndex(
            model_name='without_grndtl',
            index=models.Index(fields=['wo_grn_id', 'store_id', 'wo_grn_date', 'supplier_id', 'item_id', 'is_approved'], name='G_R_N_with__wo_grn__f2fa8f_idx'),
        ),
    ]
