# Generated by Django 4.1.5 on 2025-10-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_R_N_with_without', '0005_alter_without_grn_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='without_grn',
            name='carrying_lifting_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='without_grndtl',
            name='bonus_qty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
