# Generated by Django 4.1.5 on 2025-08-30 06:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_setup', '0002_initial'),
        ('groups_setup', '0003_initial'),
        ('organizations', '0002_initial'),
        ('section_setup', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_setup', '0003_initial'),
        ('registrations', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_merit_position_approval',
            fields=[
                ('merit_id', models.BigAutoField(default=1009900900001, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('merit_year', models.IntegerField(default=2025, editable=False)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1000450900000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1000400506000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2merit_position', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2merit_position', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2merit_position', to='groups_setup.in_groups')),
                ('is_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2merit_position', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2merit_position', to='organizations.organizationlst')),
                ('section_id', models.ManyToManyField(blank=True, null=True, related_name='section_id2merit_position', to='section_setup.in_section')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2merit_position', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2merit_position', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2merit_position', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='in_merit_position_approvaldtls',
            fields=[
                ('meritdtl_id', models.BigAutoField(default=1005600000001, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('merit_year', models.IntegerField(default=2025, editable=False)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('merit_position', models.IntegerField(blank=True, default=0, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=10000900300000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=10001036800000, editable=False, null=True)),
                ('merit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merit_id2merit_positiondtls', to='merit_app_card_print.in_merit_position_approval')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2merit_positiondtls', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2merit_positiondtls', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2merit_positiondtls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
