# Generated by Django 4.1.5 on 2025-11-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_setup', '0002_initial'),
        ('merit_app_card_print', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_merit_position_approval',
            name='section_id',
            field=models.ManyToManyField(blank=True, related_name='section_id2merit_position', to='section_setup.in_section'),
        ),
    ]
