# Generated by Django 4.1.5 on 2025-11-14 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merit_app_card_print', '0002_alter_in_merit_position_approval_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_merit_position_approval',
            name='is_half_roll_sec_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_merit_position_approval',
            name='is_half_roll_sec_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_user_id2merit_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_merit_position_approval',
            name='is_half_roll_sec_change_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
