# Generated by Django 4.1.5 on 2025-12-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merit_app_card_print', '0003_in_merit_position_approval_is_half_roll_sec_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_merit_position_approvaldtls',
            name='fail_subject_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
