# Generated by Django 4.1.5 on 2025-12-04 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject_setup', '0006_in_subjects_is_optional_wise_grade_cal'),
        ('registrations', '0004_in_registrations_is_admission_cancelled_and_more'),
        ('merit_app_card_print', '0004_in_merit_position_approvaldtls_fail_subject_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_merit_position_subjectdtls',
            fields=[
                ('msubdtl_id', models.BigAutoField(default=1859600000001, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('merit_year', models.IntegerField(default=2025, editable=False)),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_priority', models.IntegerField(blank=True, default=0, null=True)),
                ('subject_marks', models.FloatField(blank=True, default=0, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=18596003000001, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=18596004000001, editable=False, null=True)),
                ('merit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merit_id2merit_subjectdtls', to='merit_app_card_print.in_merit_position_approval')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2merit_subjectdtls', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2merit_subjectdtls', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2merit_subjectdtls', to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_id2merit_subjectdtls', to='subject_setup.in_subjects')),
            ],
        ),
    ]
