# Generated by Django 4.1.5 on 2026-09-06 06:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Card এ 01, 02 এভাবে দেখানোর জন্য ক্রম (order)', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Card এর ভেতরের ছোট বর্ণনা', validators=[django.core.validators.MinLengthValidator(10)])),
                ('icon', models.ImageField(blank=True, help_text='ঐচ্ছিক — চাইলে প্রতিটি সার্ভিসের একটা আইকন/ছবি দিতে পারেন', null=True, upload_to='services/icons/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck করলে ওয়েবসাইটে দেখাবে না')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_text', models.CharField(default='What we do', max_length=100)),
                ('heading', models.CharField(default='Services built around how Bangladeshi celebrations actually unfold', max_length=255)),
                ('sub_text', models.TextField(default='Pick a single day of coverage or hand us the whole calendar — holud through walima.')),
            ],
            options={
                'verbose_name': 'Service Section (Heading)',
                'verbose_name_plural': 'Service Section (Heading)',
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='what_we_do.service')),
            ],
            options={
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
