# Generated by Django 4.1.5 on 2026-09-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_do', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.DeleteModel(
            name='ServiceInquiry',
        ),
    ]
