# Generated by Django 4.1.5 on 2025-01-04 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_setup', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        ('drivers_setup', '0003_initial'),
        ('registrations', '0002_initial'),
        ('deliver_chalan', '0004_delivery_chalandtl_list_is_cancel_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='manual_delivery_info',
            fields=[
                ('del_info_id', models.BigAutoField(default=9990101000000, editable=False, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('is_non_register', models.BooleanField(default=False)),
                ('is_register', models.BooleanField(default=False)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('road_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_no', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('emergency_person', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1999000000100, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1999000000110, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2mdeli_info', to='organizations.branchslist')),
                ('cash_point', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2mdeli_info', to='store_setup.store')),
                ('chalan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chalan_id2mdeli_info', to='deliver_chalan.delivery_chalan_list')),
                ('driver_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_id2mdeli_info', to='drivers_setup.drivers_list')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2mdeli_info', to='organizations.organizationlst')),
                ('reg_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2mdeli_info', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2mdeli_info', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2mdeli_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
