# Generated by Django 4.1.5 on 2025-01-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_chalan', '0005_manual_delivery_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_chalan_list',
            name='is_manual_chalan',
            field=models.BooleanField(default=False),
        ),
    ]
