# Generated by Django 4.1.5 on 2025-02-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver_chalan', '0006_delivery_chalan_list_is_manual_chalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual_delivery_info',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manual_delivery_info',
            name='side_office_factory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
