# Generated by Django 4.1.5 on 2025-06-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlst',
            name='is_start_up',
            field=models.DateField(blank=True, null=True),
        ),
    ]
