# Generated by Django 4.1.5 on 2025-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationlst_is_start_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlst',
            name='service_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
