# Generated by Django 4.1.5 on 2025-06-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationlst_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlst',
            name='is_alert_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationlst',
            name='is_alert_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
