# Generated by Django 4.1.5 on 2025-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationlst_is_alert_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlst',
            name='is_delivery_chalan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationlst',
            name='is_grn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationlst',
            name='is_lp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationlst',
            name='is_mrr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationlst',
            name='ser_char_alert',
            field=models.BooleanField(default=True),
        ),
    ]
