# Generated by Django 4.1.5 on 2025-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationlst_is_delivery_chalan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationlst',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationlst',
            name='is_delivery_chalan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationlst',
            name='is_grn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationlst',
            name='is_lp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationlst',
            name='is_mrr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationlst',
            name='ser_char_alert',
            field=models.BooleanField(default=False),
        ),
    ]
