# Generated by Django 4.1.5 on 2025-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organizationlst_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlst',
            name='is_stock_recon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationlst',
            name='is_store_trans',
            field=models.BooleanField(default=False),
        ),
    ]
