# Generated by Django 4.1.5 on 2026-03-01 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0002_title_of_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages_items',
            fields=[
                ('pitem_id', models.BigAutoField(default=1550005000001, editable=False, primary_key=True, serialize=False)),
                ('pitem_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1135000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1575000020000, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2pitem', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2pitem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
