# Generated by Django 4.1.5 on 2026-03-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0003_packages_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='packages_list',
            fields=[
                ('package_id', models.BigAutoField(default=1550000000001, editable=False, primary_key=True, serialize=False)),
                ('package_title', models.CharField(blank=True, max_length=150, null=True)),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_package_price', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_offer_price', models.BooleanField(default=False)),
                ('title_caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('title_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='title_imgage')),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1772000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1255000020000, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2tofp', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2tofp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='title_of_package',
        ),
    ]
