# Generated by Django 4.1.5 on 2026-03-03 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0004_packages_list_delete_title_of_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages_list',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2package', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packages_list',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2package', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='packages_dtls',
            fields=[
                ('packagedtls_id', models.BigAutoField(default=1482000000001, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(blank=True, null=True)),
                ('elements_drescription', models.CharField(blank=True, max_length=2500, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1568000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1176000020000, editable=False, null=True)),
                ('package_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages2packagedtls', to='packages.packages_list')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2packagedtls', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2packagedtls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
