# Generated by Django 4.1.5 on 2026-03-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_alter_packages_list_ss_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages_dtls',
            name='pitem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitem_id2packagedtls', to='packages.packages_items'),
        ),
    ]
