# Generated by Django 4.1.5 on 2026-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_themes',
            fields=[
                ('login_theme_id', models.BigAutoField(default=1339710000000, editable=False, primary_key=True, serialize=False)),
                ('login_theme_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1456700000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=189670000000, editable=False, null=True)),
            ],
        ),
    ]
