# Generated by Django 4.1.5 on 2024-11-03 14:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_pos', '0006_reward_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward_points',
            name='inv_id',
        ),
        migrations.CreateModel(
            name='reward_pointsdtls',
            fields=[
                ('rewarddtls_id', models.BigAutoField(default=3312000000000, editable=False, primary_key=True, serialize=False)),
                ('reward_dtls_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('reward_dtls_balance', models.FloatField(blank=True, default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=2335300000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=3576400000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2reward_dtls_point', to='organizations.branchslist')),
                ('inv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_pos.invoice_list')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2reward_dtls_point', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2reward_dtls_point', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2reward_dtls_point', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
