# Generated by Django 4.1.5 on 2024-11-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_initial'),
        ('item_pos', '0007_remove_reward_points_inv_id_reward_pointsdtls'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward_points',
            name='reg_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2reward_point', to='registrations.in_registrations'),
        ),
        migrations.AddField(
            model_name='reward_pointsdtls',
            name='reg_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2reward_dtls_point', to='registrations.in_registrations'),
        ),
    ]
