# Generated by Django 4.1.5 on 2024-11-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_pos', '0008_reward_points_reg_id_reward_pointsdtls_reg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward_points',
            name='reward_date',
        ),
    ]
