# Generated by Django 4.1.5 on 2025-01-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_pos', '0010_payment_list_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_list',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice_list',
            name='side_office_factory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
