# Generated by Django 4.1.5 on 2025-02-10 06:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers_setup', '0003_initial'),
        ('item_pos', '0011_invoice_list_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_others_exps',
            name='is_carrying_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='carrying_cost_payments',
            fields=[
                ('c_cost_id', models.BigAutoField(default=4411220000000, editable=False, primary_key=True, serialize=False)),
                ('c_cost_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('c_cost_amt', models.FloatField(blank=True, default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('descriptions', models.CharField(blank=True, max_length=100, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=5577880000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=6688990000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2c_cost_pay', to='organizations.branchslist')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_id2c_cost_pay', to='drivers_setup.drivers_list')),
                ('inv_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_pos.invoice_list')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2c_cost_pay', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2c_cost_pay', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2c_cost_pay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
