# Generated by Django 4.1.5 on 2025-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_pos', '0012_rent_others_exps_is_carrying_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrying_cost_payments',
            name='pay_inv_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
