# Generated by Django 4.1.5 on 2025-02-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_pos', '0013_carrying_cost_payments_pay_inv_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrying_cost_payments',
            name='inv_id',
        ),
    ]
