# Generated by Django 4.1.5 on 2025-02-14 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_branchslist_is_main_branch_branchslist_is_sub_branch'),
        ('item_pos', '0014_remove_carrying_cost_payments_inv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='without_invoice_collection',
            fields=[
                ('wo_coll_id', models.BigAutoField(default=2000220020000, editable=False, primary_key=True, serialize=False)),
                ('coll_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('collection_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('collection_type', models.CharField(blank=True, max_length=10, null=True)),
                ('collection_amt', models.FloatField(blank=True, default=0)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('road_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sector_no', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('side_office_factory', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('emergency_person', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('card_info', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=2344000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=334560000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2wo_inv_coll', to='organizations.branchslist')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2wo_inv_coll', to='organizations.organizationlst')),
                ('reg_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2wo_inv_coll', to='registrations.in_registrations')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2wo_inv_coll', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2wo_inv_coll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
