# Generated by Django 4.1.5 on 2025-02-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_pos', '0015_without_invoice_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='without_invoice_collection',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
