# Generated by Django 4.1.5 on 2025-10-06 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organizationlst_is_stock_recon_and_more'),
        ('item_pos', '0016_without_invoice_collection_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedtl_list',
            name='invoice_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='carrying_cost_payments',
            name='c_cost_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='carrying_cost_payments',
            name='c_cost_id',
            field=models.BigAutoField(db_index=True, default=4411220000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carrying_cost_payments',
            name='pay_inv_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrying_cost_payments',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='carrying_cost_payments',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='driver_mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='inv_id',
            field=models.BigAutoField(db_index=True, default=1000110010000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='invoice_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='is_b2b_clients',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='is_cancel',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='is_general_bill',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_list',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoicedtl_list',
            name='invdtl_id',
            field=models.BigAutoField(db_index=True, default=1100000000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoicedtl_list',
            name='is_cancel',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='item_fav_list',
            name='fav_id',
            field=models.BigAutoField(db_index=True, default=129120000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_list',
            name='collection_mode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment_list',
            name='pay_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='payment_list',
            name='pay_id',
            field=models.BigAutoField(db_index=True, default=1110000000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_list',
            name='pay_mode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment_list',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment_list',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rent_others_exps',
            name='other_exps_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='rent_others_exps',
            name='other_exps_id',
            field=models.BigAutoField(db_index=True, default=1321000000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rent_others_exps',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='rent_others_exps',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reward_points',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reward_points',
            name='reward_id',
            field=models.BigAutoField(db_index=True, default=2412000000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reward_points',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reward_points',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reward_pointsdtls',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reward_pointsdtls',
            name='reward_dtls_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reward_pointsdtls',
            name='rewarddtls_id',
            field=models.BigAutoField(db_index=True, default=3312000000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reward_pointsdtls',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reward_pointsdtls',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='without_invoice_collection',
            name='coll_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='without_invoice_collection',
            name='collection_mode',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='without_invoice_collection',
            name='collection_type',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='without_invoice_collection',
            name='ss_created_on',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='without_invoice_collection',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='without_invoice_collection',
            name='wo_coll_id',
            field=models.BigAutoField(db_index=True, default=2000220020000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterIndexTogether(
            name='invoice_list',
            index_together={('org_id', 'branch_id', 'invoice_date')},
        ),
        migrations.AddIndex(
            model_name='carrying_cost_payments',
            index=models.Index(fields=['org_id', 'branch_id', 'c_cost_date'], name='item_pos_ca_org_id__e89098_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice_list',
            index=models.Index(fields=['org_id', 'branch_id', 'invoice_date'], name='item_pos_in_org_id__43006a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice_list',
            index=models.Index(fields=['mobile_number'], name='item_pos_in_mobile__4fd40f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice_list',
            index=models.Index(fields=['is_cancel'], name='item_pos_in_is_canc_3c4386_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicedtl_list',
            index=models.Index(fields=['inv_id', 'item_id', 'store_id', 'stock_id', 'item_uom_id'], name='item_pos_in_inv_id__842df2_idx'),
        ),
        migrations.AddIndex(
            model_name='item_fav_list',
            index=models.Index(fields=['item_id', 'user_id'], name='item_pos_it_item_id_372918_idx'),
        ),
        migrations.AddIndex(
            model_name='payment_list',
            index=models.Index(fields=['inv_id', 'pay_date'], name='item_pos_pa_inv_id__1f25b1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment_list',
            index=models.Index(fields=['pay_mode'], name='item_pos_pa_pay_mod_cf0574_idx'),
        ),
        migrations.AddIndex(
            model_name='rent_others_exps',
            index=models.Index(fields=['org_id', 'branch_id', 'other_exps_date'], name='item_pos_re_org_id__e0961b_idx'),
        ),
        migrations.AddIndex(
            model_name='reward_points',
            index=models.Index(fields=['org_id', 'branch_id', 'reg_id'], name='item_pos_re_org_id__1d1359_idx'),
        ),
        migrations.AddIndex(
            model_name='reward_pointsdtls',
            index=models.Index(fields=['org_id', 'branch_id', 'reward_dtls_date'], name='item_pos_re_org_id__9637bc_idx'),
        ),
        migrations.AddIndex(
            model_name='without_invoice_collection',
            index=models.Index(fields=['org_id', 'branch_id', 'reg_id', 'coll_date'], name='item_pos_wi_org_id__4d1bfa_idx'),
        ),
    ]
