# Generated by Django 4.1.5 on 2025-08-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_setup', '0004_items_default_store'),
        ('store_setup', '0002_initial'),
        ('organizations', '0008_alter_organizationlst_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_transfer_list',
            fields=[
                ('stock_trans_id', models.BigAutoField(default=1009090000000, editable=False, primary_key=True, serialize=False)),
                ('stock_trans_no', models.CharField(editable=False, max_length=15)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, default='', max_length=300)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1009900900000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1008800090000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2stock_transfer', to='organizations.branchslist')),
                ('id_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2stock_transfer', to='organizations.organizationlst')),
                ('is_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2stock_transfer', to=settings.AUTH_USER_MODEL)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2stock_transfer', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2stock_transfer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stock_transfer_listdtl',
            fields=[
                ('stock_transdtl_id', models.BigAutoField(default=1007800900000, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_qty', models.FloatField(blank=True, null=True)),
                ('item_batch', models.CharField(blank=True, max_length=150, null=True)),
                ('item_exp_date', models.DateField(blank=True, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1299900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112999000000, editable=False, null=True)),
                ('from_store', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_store2transferDtl', to='store_setup.store')),
                ('item_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_id2transferDtl', to='item_setup.items')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2transferDtl', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2transferDtl', to=settings.AUTH_USER_MODEL)),
                ('stock_trans_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfer_id2transferDtl', to='store_transfers.stock_transfer_list')),
                ('to_store', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_store2transferDtl', to='store_setup.store')),
            ],
        ),
    ]
