# Generated by Django 4.1.5 on 2025-08-06 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_setup', '0002_initial'),
        ('store_transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_transfer_list',
            name='from_store',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_store2stock_transfer', to='store_setup.store'),
        ),
        migrations.AddField(
            model_name='stock_transfer_list',
            name='to_store',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_store2stock_transfer', to='store_setup.store'),
        ),
    ]
