# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_setup', '0002_initial'),
        ('class_setup', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_subjects',
            fields=[
                ('subjects_id', models.BigAutoField(default=1266440000000, editable=False, primary_key=True, serialize=False)),
                ('subjects_no', models.CharField(blank=True, max_length=50, null=True)),
                ('subjects_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_marks', models.IntegerField(blank=True, null=True)),
                ('is_pass_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_not_countable', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=17741000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=188810000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2in_subjects', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2in_subjects', to='groups_setup.in_groups')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_subjects', to='organizations.organizationlst')),
            ],
        ),
    ]
