# Generated by Django 4.1.5 on 2025-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_subjects',
            name='is_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
