# Generated by Django 4.1.5 on 2025-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_subjects',
            name='subjects_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
