# Generated by Django 4.1.5 on 2025-07-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0002_in_subjects_is_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_subjects',
            name='is_pass_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
