# Generated by Django 4.1.5 on 2025-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0003_alter_in_subjects_subjects_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_subjects',
            name='subjects_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
