# Generated by Django 4.1.5 on 2025-07-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0003_in_subjects_is_pass_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_subjects',
            name='is_pass_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
