# Generated by Django 4.1.5 on 2025-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0004_alter_in_subjects_subjects_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_subjects',
            name='is_applicable_pass_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_subjects',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
