# Generated by Django 4.1.5 on 2025-08-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_setup', '0005_in_subjects_is_applicable_pass_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_subjects',
            name='is_optional_wise_grade_cal',
            field=models.BooleanField(default=False),
        ),
    ]
