# Generated by Django 4.1.5 on 2024-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase_return', '0004_alter_lp_return_details_lp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lp_return_details',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
