# Generated by Django 4.1.5 on 2025-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase_return', '0005_lp_return_details_is_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lp_return_details',
            name='is_returned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lp_return_details',
            name='lprdtl_id',
            field=models.BigAutoField(db_index=True, default=6677100000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lp_return_details',
            name='returned_date',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lp_return_details',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lp_return_details',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='lp_return_details',
            index=models.Index(fields=['lp_id', 'item_id', 'is_returned'], name='local_purch_lp_id_i_260128_idx'),
        ),
        migrations.AddIndex(
            model_name='lp_return_details',
            index=models.Index(fields=['store_id'], name='local_purch_store_i_a08c9b_idx'),
        ),
    ]
