# Generated by Django 4.1.5 on 2026-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='How it works', help_text='ছোট লেবেল, যেমন: How it works', max_length=100)),
                ('heading', models.CharField(default='From first message to final gallery', help_text='মূল H2 heading', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Section (Heading)',
                'verbose_name_plural': 'Process Section (Heading)',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='ধাপের নাম্বার, যেমন: 1, 2, 3 (অটো 01, 02 আকারে দেখাবে)')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='সিরিয়াল অনুযায়ী সাজানোর জন্য (ছোট নাম্বার আগে দেখাবে)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order', 'step_number'],
            },
        ),
    ]
