# Generated by Django 4.1.5 on 2025-07-26 03:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0007_in_registrations_is_versions'),
        ('organizations', '0002_initial'),
        ('groups_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section_setup', '0001_initial'),
        ('shift_setup', '0001_initial'),
        ('exam_type', '0002_in_exam_type_is_half_yearly_in_exam_type_is_yearly'),
        ('class_setup', '0002_in_class_allow_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_student_attendant',
            fields=[
                ('attendant_id', models.BigAutoField(default=1003030303000, editable=False, primary_key=True, serialize=False)),
                ('trans_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('attendant_year', models.IntegerField(default=2025, editable=False)),
                ('working_days', models.IntegerField(blank=True, default=0, null=True)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=10040400400000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1000500505000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2in_student_att', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2in_student_att', to='class_setup.in_class')),
                ('exam_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type_id2in_student_att', to='exam_type.in_exam_type')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2in_student_att', to='groups_setup.in_groups')),
                ('is_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2in_student_att', to=settings.AUTH_USER_MODEL)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_student_att', to='organizations.organizationlst')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2in_student_att', to='section_setup.in_section')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2in_student_att', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_student_att', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_student_att', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='in_student_attendantdtls',
            fields=[
                ('attendantdtl_id', models.BigAutoField(default=1000220202000, editable=False, primary_key=True, serialize=False)),
                ('trans_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('attendant_year', models.IntegerField(default=2025, editable=False)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('section_name', models.CharField(blank=True, max_length=20, null=True)),
                ('shift_name', models.CharField(blank=True, max_length=20, null=True)),
                ('groups_name', models.CharField(blank=True, max_length=20, null=True)),
                ('attendant_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=10000100303000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1000400400400, editable=False, null=True)),
                ('attendant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendant_id2in_student_attdtl', to='attendant_manager.in_student_attendant')),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2in_student_attdtl', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2in_student_attdtl', to='class_setup.in_class')),
                ('exam_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type_id2in_student_attdtl', to='exam_type.in_exam_type')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2in_student_attdtl', to='groups_setup.in_groups')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_student_attdtl', to='organizations.organizationlst')),
                ('reg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2in_student_attdtl', to='registrations.in_registrations')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2in_student_attdtl', to='section_setup.in_section')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2in_student_attdtl', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_student_attdtl', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_student_attdtl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
