# Generated by Django 4.1.5 on 2025-08-16 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='in_student_attendant',
            fields=[
                ('attendant_id', models.BigAutoField(default=1003030303000, editable=False, primary_key=True, serialize=False)),
                ('trans_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('attendant_year', models.IntegerField(default=2025, editable=False)),
                ('working_days', models.IntegerField(blank=True, default=0, null=True)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=10040400400000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1000500505000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_student_attendantdtls',
            fields=[
                ('attendantdtl_id', models.BigAutoField(default=1000220202000, editable=False, primary_key=True, serialize=False)),
                ('trans_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('attendant_year', models.IntegerField(default=2025, editable=False)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('section_name', models.CharField(blank=True, max_length=20, null=True)),
                ('shift_name', models.CharField(blank=True, max_length=20, null=True)),
                ('groups_name', models.CharField(blank=True, max_length=20, null=True)),
                ('attendant_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('is_half_yearly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.CharField(blank=True, max_length=50, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=10000100303000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1000400400400, editable=False, null=True)),
                ('attendant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendant_id2in_student_attdtl', to='attendant_manager.in_student_attendant')),
            ],
        ),
    ]
