# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_type', '0001_initial'),
        ('groups_setup', '0001_initial'),
        ('class_setup', '0001_initial'),
        ('organizations', '0001_initial'),
        ('attendant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2in_student_attdtl', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2in_student_attdtl', to='class_setup.in_class'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='exam_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type_id2in_student_attdtl', to='exam_type.in_exam_type'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='groups_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2in_student_attdtl', to='groups_setup.in_groups'),
        ),
    ]
