# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_setup', '0001_initial'),
        ('section_setup', '0001_initial'),
        ('exam_type', '0002_initial'),
        ('groups_setup', '0002_initial'),
        ('class_setup', '0002_initial'),
        ('registrations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('attendant_manager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2in_student_attdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_student_attdtl', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='reg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_id2in_student_attdtl', to='registrations.in_registrations'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2in_student_attdtl', to='section_setup.in_section'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='shifts_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2in_student_attdtl', to='shift_setup.in_shifts'),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_student_attdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_student_attendantdtls',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_student_attdtl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2in_student_att', to='organizations.branchslist'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2in_student_att', to='class_setup.in_class'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='exam_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type_id2in_student_att', to='exam_type.in_exam_type'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='groups_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2in_student_att', to='groups_setup.in_groups'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='is_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2in_student_att', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_student_att', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2in_student_att', to='section_setup.in_section'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='shifts_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2in_student_att', to='shift_setup.in_shifts'),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_student_att', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_student_attendant',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_student_att', to=settings.AUTH_USER_MODEL),
        ),
    ]
