# Generated by Django 4.1.5 on 2026-02-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='photos_gallery',
            fields=[
                ('phgallery_id', models.BigAutoField(default=1450000000001, editable=False, primary_key=True, serialize=False)),
                ('gallery_name', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_title', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1342000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1533000020000, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2phgallery_id', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2phgallery_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='photos_gallery_dtls',
            fields=[
                ('phgdtls_id', models.BigAutoField(default=1350000000001, editable=False, primary_key=True, serialize=False)),
                ('photos', models.ImageField(blank=True, max_length=255, null=True, upload_to='photos_gallery')),
                ('is_cover_photo', models.BooleanField(default=False)),
                ('is_thumbnail_photo', models.BooleanField(default=False)),
                ('photo_description', models.CharField(blank=True, max_length=500, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1232000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1351000020000, editable=False, null=True)),
                ('phgallery_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phgallery2phgdtls', to='photo_gallery.photos_gallery')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2phgdtls', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2phgdtls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
