# Generated by Django 4.1.5 on 2026-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos_gallery_dtls',
            name='photos_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
