# Generated by Django 4.1.5 on 2026-09-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_photos_gallery_dtls_photos_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos_gallery',
            old_name='gallery_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='photos_gallery',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='photos_gallery',
            name='thumbnail_title',
        ),
        migrations.AddField(
            model_name='photos_gallery',
            name='photo_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('holud_mehndi', 'Holud & Mehndi'), ('pre_wedding', 'Pre-Wedding'), ('engagement', 'Engagement'), ('corporate', 'Corporate'), ('birthday_family', 'Birthday & Family'), ('portrait', 'Portrait'), ('events', 'Events'), ('videography', 'Videography'), ('drone', 'Drone')], default='wedding', max_length=100),
        ),
    ]
