# Generated by Django 4.1.5 on 2026-09-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_rename_gallery_name_photos_gallery_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos_gallery',
            name='ss_created_session',
        ),
        migrations.RemoveField(
            model_name='photos_gallery',
            name='ss_modified_session',
        ),
        migrations.RemoveField(
            model_name='photos_gallery_dtls',
            name='ss_created_session',
        ),
        migrations.RemoveField(
            model_name='photos_gallery_dtls',
            name='ss_modified_session',
        ),
        migrations.AlterField(
            model_name='photos_gallery',
            name='phgallery_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photos_gallery_dtls',
            name='phgdtls_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
