# Generated by Django 4.1.5 on 2026-09-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0004_remove_photos_gallery_ss_created_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos_gallery',
            name='photo_type',
            field=models.CharField(choices=[('photography', 'Photography'), ('wedding', 'Wedding'), ('holud_mehndi', 'Holud & Mehndi'), ('pre_wedding', 'Pre-Wedding'), ('engagement', 'Engagement'), ('corporate', 'Corporate'), ('birthday_family', 'Birthday & Family'), ('portrait', 'Portrait'), ('events', 'Events'), ('videography', 'Videography'), ('drone', 'Drone')], default='photography', max_length=100),
        ),
    ]
