# Generated by Django 4.1.5 on 2026-09-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0005_alter_photos_gallery_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos_gallery',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='photos_gallery',
            name='is_album',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photos_gallery',
            name='is_recent_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photos_gallery',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
