# Generated by Django 4.1.5 on 2026-09-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0006_photos_gallery_description_photos_gallery_is_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos_gallery',
            name='photo_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('pre_post_wedding', 'Pre -Post Wedding'), ('fashion', 'Fashion'), ('commercial', 'Commercial'), ('corporate', 'Corporate'), ('portrait', 'Portrait'), ('conceptual_art_theme', 'Conceptual Art / Theme base'), ('maternity_family', 'Maternity & Family'), ('real_estate_architecture', 'Real Estate & Architecture'), ('food_beverage', 'Food & Beverage'), ('events', 'Events'), ('specialized_photography', 'Specialized Photography'), ('aerial_advanced_production', 'Aerial & Advanced Production')], default='photography', max_length=150),
        ),
    ]
