# Generated by Django 4.1.5 on 2025-08-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_transfers', '0001_initial'),
        ('stock_list', '0005_stock_lists_is_cancel_qty_stock_lists_lprdtl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_lists',
            name='stock_trans_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_trans_id2stock_lists', to='store_transfers.stock_transfer_list'),
        ),
        migrations.AddField(
            model_name='stock_lists',
            name='stock_transdtl_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_transdtl_id2stock_lists', to='store_transfers.stock_transfer_listdtl'),
        ),
    ]
