# Generated by Django 4.1.5 on 2026-03-06 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0006_packages_dtls_pitem_id'),
        ('booking_us', '0004_slot_details_is_full_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('order_id', models.BigAutoField(default=3999000000001, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=3999000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=3999000020000, editable=False, null=True)),
                ('shoot_type', models.JSONField(default=list)),
                ('venue_name', models.CharField(max_length=255)),
                ('guest_number', models.CharField(max_length=50)),
                ('about_you', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('your_planned', models.TextField(blank=True, null=True)),
                ('is_other_photographer', models.BooleanField(default=False)),
                ('discover_type', models.JSONField(default=list)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_list',
                'ordering': ['-ss_created_on'],
            },
        ),
        migrations.CreateModel(
            name='OrderPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order_list.orderlist')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='packages.packages_list')),
            ],
            options={
                'db_table': 'order_package_price',
            },
        ),
        migrations.AddField(
            model_name='orderlist',
            name='package_id',
            field=models.ManyToManyField(blank=True, related_name='package_id2orderlst', through='order_list.OrderPackagePrice', to='packages.packages_list'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='schedule_id',
            field=models.ManyToManyField(blank=True, related_name='schedule_id2orderlst', to='booking_us.eventschedule'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2order', to=settings.AUTH_USER_MODEL),
        ),
    ]
