# Generated by Django 4.1.5 on 2026-09-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='whoWeAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker_text', models.CharField(default='Who we are', max_length=100)),
                ('subtitle', models.CharField(default='Bridal Harmony', help_text='H3 text', max_length=150)),
                ('title_main', models.CharField(default='Premium Class Photography', help_text='H2 er age er part', max_length=200)),
                ('title_highlight', models.CharField(default='&', help_text='<em> tag er bhitorer text', max_length=50)),
                ('title_after', models.CharField(default='Cinematography Services', help_text='H2 er pore er part', max_length=200)),
                ('description', models.TextField(default="Bridal Harmony is a team of experienced professional photographers, cinematographers and photo-book experts dedicated to creating stunning, authentic stories of people's lives.")),
                ('note', models.TextField(default='From intimate family moments to grand celebrations, we capture every frame with intention, emotion and cinematic detail.')),
                ('stats_intro_label', models.CharField(default='Our journey', max_length=100)),
                ('stats_intro_text', models.TextField(default='More than a decade of capturing moments across Bangladesh.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Who We Are',
                'verbose_name_plural': 'Who We Are',
            },
        ),
        migrations.CreateModel(
            name='StatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Since, Events, Photos, Happy Clients', max_length=50)),
                ('target_number', models.PositiveIntegerField(help_text='Counter animation er target value, e.g. 2013, 6000, 800, 40')),
                ('suffix', models.CharField(blank=True, help_text='e.g. +  or  k+ (khali rakhle kichu dekhabe na)', max_length=10, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='stat-featured class add hobe kina')),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='who_we_are.whoweare')),
            ],
            options={
                'verbose_name': 'Stat Card',
                'verbose_name_plural': 'Stat Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
