# Generated by Django 4.1.5 on 2026-09-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_we_are', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statcard',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g. +  or  k+ (khali rakhle kichu dekhabe na)', max_length=10),
        ),
    ]
