# Generated by Django 4.1.5 on 2025-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_setup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_list',
            name='command_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
