# Generated by Django 4.1.5 on 2025-05-12 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_exam_modes',
            fields=[
                ('exam_mode_id', models.BigAutoField(default=1647890000000, editable=False, primary_key=True, serialize=False)),
                ('is_cq_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_cq_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_cq_active', models.BooleanField(default=False)),
                ('is_mcq_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_mcq_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_mcq_active', models.BooleanField(default=False)),
                ('is_written_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_written_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_written_active', models.BooleanField(default=False)),
                ('is_practical_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_practical_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_practical_active', models.BooleanField(default=False)),
                ('is_oral_name', models.CharField(blank=True, max_length=20, null=True)),
                ('is_oral_number', models.IntegerField(blank=True, default=0, null=True)),
                ('is_oral_active', models.BooleanField(default=False)),
                ('is_common', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1936900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=134891000000, editable=False, null=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_exam_modes', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_exam_modes', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_exam_modes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
