# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaults_exam_modes',
            fields=[
                ('def_mode_id', models.BigAutoField(default=1880800000000, editable=False, primary_key=True, serialize=False)),
                ('is_mode_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1936900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=134891000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamModeTypeMap',
            fields=[
                ('xm_m_t_map_id', models.BigAutoField(default=1500550000000, editable=False, primary_key=True, serialize=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1255500000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=186666000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_exam_modes',
            fields=[
                ('exam_mode_id', models.BigAutoField(default=1647890000000, editable=False, primary_key=True, serialize=False)),
                ('is_default_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('is_pass_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_common', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1936900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=134891000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_letter_grade_mode',
            fields=[
                ('grade_id', models.BigAutoField(default=1990990000000, editable=False, primary_key=True, serialize=False)),
                ('is_grade_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1249700000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=187634000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_letter_gradeFiftyMap',
            fields=[
                ('fifty_map_id', models.BigAutoField(default=1700770000000, editable=False, primary_key=True, serialize=False)),
                ('from_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('to_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1288900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=185677000000, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='in_letter_gradeHundredMap',
            fields=[
                ('hundred_map_id', models.BigAutoField(default=1700770000000, editable=False, primary_key=True, serialize=False)),
                ('from_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('to_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1288900000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=185677000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2hundred_map', to='class_setup.in_class')),
                ('grade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_id2hundred_map', to='defaults_exam_mode.in_letter_grade_mode')),
            ],
        ),
    ]
