# Generated by Django 4.1.5 on 2025-05-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_exam_mode', '0002_in_exam_modes_class_id_in_exam_modes_groups_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_exam_modes',
            old_name='is_cq_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='in_exam_modes',
            old_name='is_cq_number',
            new_name='is_default_marks',
        ),
        migrations.RenameField(
            model_name='in_exam_modes',
            old_name='is_cq_name',
            new_name='is_exam_modes',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='groups_id',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_mcq_active',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_mcq_name',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_mcq_number',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_oral_active',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_oral_name',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_oral_number',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_practical_active',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_practical_name',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_practical_number',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_written_active',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_written_name',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='is_written_number',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='shift_id',
        ),
        migrations.RemoveField(
            model_name='in_exam_modes',
            name='subjects_id',
        ),
    ]
