# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_setup', '0001_initial'),
        ('exam_type', '0002_initial'),
        ('class_setup', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('defaults_exam_mode', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_letter_gradehundredmap',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2hundred_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_letter_gradehundredmap',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2hundred_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_letter_gradefiftymap',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2fifty_map', to='class_setup.in_class'),
        ),
        migrations.AddField(
            model_name='in_letter_gradefiftymap',
            name='grade_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_id2fifty_map', to='defaults_exam_mode.in_letter_grade_mode'),
        ),
        migrations.AddField(
            model_name='in_letter_gradefiftymap',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2fifty_map', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='in_letter_gradefiftymap',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2fifty_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_letter_gradefiftymap',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2fifty_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_letter_grade_mode',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2letter_grade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_letter_grade_mode',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2letter_grade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2exam_modes', to='class_setup.in_class'),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='exam_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type_id2exam_modes', to='exam_type.in_exam_type'),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='is_exam_modes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='def_mode_id2exam_modes', to='defaults_exam_mode.defaults_exam_modes'),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2exam_modes', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2in_exam_modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2in_exam_modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='in_exam_modes',
            name='subjects_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects_id2exam_modes', to='subject_setup.in_subjects'),
        ),
        migrations.AddField(
            model_name='exammodetypemap',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2xmmt_map', to='class_setup.in_class'),
        ),
        migrations.AddField(
            model_name='exammodetypemap',
            name='def_mode_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='def_mode_id2mmt_map', to='defaults_exam_mode.defaults_exam_modes'),
        ),
        migrations.AddField(
            model_name='exammodetypemap',
            name='exam_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_type_id2mmt_map', to='exam_type.in_exam_type'),
        ),
        migrations.AddField(
            model_name='exammodetypemap',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2xmmt_map', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='exammodetypemap',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2mmt_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exammodetypemap',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2mmt_map', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaults_exam_modes',
            name='ss_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2def_mode', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaults_exam_modes',
            name='ss_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2def_mode', to=settings.AUTH_USER_MODEL),
        ),
    ]
