# Generated by Django 4.1.5 on 2025-08-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_exam_mode', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_letter_gradefiftymap',
            name='grade_point',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='in_letter_gradehundredmap',
            name='grade_point',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
