# Generated by Django 4.1.5 on 2025-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_exam_mode', '0004_in_letter_gradefiftymap_grade_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults_exam_modes',
            name='order_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
