# Generated by Django 4.1.5 on 2025-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_exam_mode', '0005_defaults_exam_modes_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults_exam_modes',
            name='short_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
