# Generated by Django 4.1.5 on 2025-08-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_exam_mode', '0006_defaults_exam_modes_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_letter_gradefiftymap',
            name='from_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradefiftymap',
            name='to_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradehundredmap',
            name='from_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradehundredmap',
            name='to_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
