# Generated by Django 4.1.5 on 2025-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_exam_mode', '0007_alter_in_letter_gradefiftymap_from_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_letter_gradefiftymap',
            name='from_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradefiftymap',
            name='grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradefiftymap',
            name='to_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradehundredmap',
            name='from_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradehundredmap',
            name='grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_letter_gradehundredmap',
            name='to_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
