# Generated by Django 4.1.5 on 2025-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_bill_receipt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_bill_receipts',
            name='chalan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='in_bill_receipts',
            name='receipt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
