# Generated by Django 4.1.5 on 2026-03-03 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('schedule_id', models.BigAutoField(default=1999000000001, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('slot_title', models.CharField(choices=[('Full Day', 'Full Day'), ('Morning Slot', 'Morning Slot'), ('Afternoon Slot', 'Afternoon Slot'), ('Evening Slot', 'Evening Slot')], max_length=100)),
                ('status', models.CharField(choices=[('Free', 'Free'), ('Booked', 'Booked')], default='Free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=2999000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=2999000020000, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2schedule', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_schedule',
                'ordering': ['-event_date'],
                'unique_together': {('event_date', 'slot_title')},
            },
        ),
    ]
