# Generated by Django 4.1.5 on 2026-03-04 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Details',
            fields=[
                ('slot_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('slot_name', models.CharField(blank=True, max_length=150, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2slotdtl', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2slotdtl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slot_details',
                'ordering': ['-slot_id'],
            },
        ),
    ]
