# Generated by Django 4.1.5 on 2026-03-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_us', '0002_slot_details'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='slot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_id2schedule', to='booking_us.slot_details'),
        ),
        migrations.AlterUniqueTogether(
            name='eventschedule',
            unique_together={('event_date', 'slot_id')},
        ),
        migrations.RemoveField(
            model_name='eventschedule',
            name='slot_title',
        ),
    ]
