# Generated by Django 4.1.5 on 2026-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_us', '0003_alter_eventschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_details',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
