# Generated by Django 4.1.5 on 2025-08-16 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_setup', '0002_initial'),
        ('class_setup', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_registrations',
            fields=[
                ('reg_id', models.BigAutoField(default=1112200000000, editable=False, primary_key=True, serialize=False)),
                ('students_no', models.CharField(editable=False, max_length=15)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=30, null=True)),
                ('co_name', models.CharField(blank=True, max_length=100, null=True)),
                ('co_relationship', models.CharField(blank=True, max_length=30, null=True)),
                ('co_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('thana_upazila', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('identity_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_con_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_con_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_con_rel', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_con_address', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_img', models.ImageField(blank=True, max_length=50, null=True, upload_to='in_reg_profile')),
                ('reg_date', models.DateField(default=datetime.datetime.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1990800000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1529200000000, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2in_reg', to='organizations.branchslist')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2in_reg', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2in_reg', to='groups_setup.in_groups')),
            ],
        ),
    ]
