# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_setup', '0001_initial'),
        ('subject_setup', '0001_initial'),
        ('registrations', '0001_initial'),
        ('section_setup', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_registrations',
            name='is_optional_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects_id2in_reg', to='subject_setup.in_subjects'),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_reg', to='organizations.organizationlst'),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='section_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2in_reg', to='section_setup.in_section'),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_id2in_reg', to='shift_setup.in_shifts'),
        ),
    ]
