# Generated by Django 4.1.5 on 2025-12-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_registrations',
            name='is_admission_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_court_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_expelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_fail_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_family_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_family_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_financial_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_government_directive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_lack_of_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_misbehavior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_personal_health_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_policy_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_promoted_passed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_rusticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_transferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_registrations',
            name='is_unauthorized_absent',
            field=models.BooleanField(default=False),
        ),
    ]
