# Generated by Django 4.1.5 on 2025-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_in_registrations_class_id_in_registrations_groups_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_registrations',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
