# Generated by Django 4.1.5 on 2025-05-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_in_registrations_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_registrations',
            old_name='customer_no',
            new_name='students_no',
        ),
        migrations.AlterUniqueTogether(
            name='in_registrations',
            unique_together={('reg_id', 'students_no')},
        ),
    ]
