# Generated by Django 4.1.5 on 2025-05-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('registrations', '0005_rename_customer_no_in_registrations_students_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_registrations',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2in_reg', to='organizations.branchslist'),
        ),
    ]
