# Generated by Django 4.1.5 on 2025-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_in_registrations_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_registrations',
            name='is_versions',
            field=models.BooleanField(default=True),
        ),
    ]
