# Generated by Django 4.1.5 on 2025-02-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_management', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_transactions',
            name='credit_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
