# Generated by Django 4.1.5 on 2025-03-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_management', '0004_alter_credit_transactions_credit_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_transactions',
            name='descriptions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
