# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='in_class',
            fields=[
                ('class_id', models.BigAutoField(default=123020000000, editable=False, primary_key=True, serialize=False)),
                ('class_no', models.CharField(blank=True, max_length=50, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('allow_groups', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1231000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112350000000, editable=False, null=True)),
            ],
        ),
    ]
