# Generated by Django 4.1.5 on 2025-02-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_transection', '0005_paymentsdtls'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsdtls',
            name='is_reg_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentsdtls',
            name='is_supplier_party',
            field=models.BooleanField(default=False),
        ),
    ]
