# Generated by Django 4.1.5 on 2025-02-24 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_setup', '0002_initial'),
        ('clients_transection', '0006_paymentsdtls_is_reg_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsdtls',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_id2paydtls', to='supplier_setup.suppliers'),
        ),
    ]
