# Generated by Django 4.1.5 on 2025-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_transection', '0007_paymentsdtls_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening_balance',
            name='is_credited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='opening_balance',
            name='is_debited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='opening_balance',
            name='opb_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='opening_balance',
            name='opb_id',
            field=models.BigAutoField(db_index=True, default=3088000000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opening_balance',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='opening_balance',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentsdtls',
            name='is_reg_client',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='paymentsdtls',
            name='is_supplier_party',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='paymentsdtls',
            name='pay_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentsdtls',
            name='pay_id',
            field=models.BigAutoField(db_index=True, default=1142340000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentsdtls',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentsdtls',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='opening_balance',
            index=models.Index(fields=['org_id', 'branch_id', 'reg_id', 'is_debited', 'opb_date'], name='clients_tra_org_id__a7877d_idx'),
        ),
        migrations.AddIndex(
            model_name='opening_balance',
            index=models.Index(fields=['org_id', 'branch_id', 'reg_id', 'is_credited', 'opb_date'], name='clients_tra_org_id__25872e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsdtls',
            index=models.Index(fields=['org_id', 'branch_id', 'reg_id', 'pay_date', 'is_reg_client'], name='clients_tra_org_id__737507_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsdtls',
            index=models.Index(fields=['org_id', 'branch_id', 'reg_id', 'pay_date', 'is_supplier_party'], name='clients_tra_org_id__3292d9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsdtls',
            index=models.Index(fields=['supplier_id', 'pay_date', 'is_supplier_party'], name='clients_tra_supplie_983989_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsdtls',
            index=models.Index(fields=['pay_mode'], name='clients_tra_pay_mod_4cd021_idx'),
        ),
    ]
