# Generated by Django 4.1.5 on 2025-08-29 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_setup', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_class_wise_merit_policy',
            fields=[
                ('clsswisep_id', models.BigAutoField(default=1234014000000, editable=False, primary_key=True, serialize=False)),
                ('is_average_gpa', models.IntegerField(blank=True, help_text='Sorting priority for GPA', null=True)),
                ('total_obtained_marks', models.IntegerField(blank=True, help_text='Sorting priority for Total Marks', null=True)),
                ('roll_no', models.IntegerField(blank=True, help_text='Sorting priority for Roll No', null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1135700000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=145780000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2clsswisepm', to='class_setup.in_class')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2clsswisepm', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2clsswisepm', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2clsswisepm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
