# Generated by Django 4.1.5 on 2025-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_class_wise_merit_policy',
            old_name='is_average_gpa',
            new_name='is_average_gpa_priority',
        ),
        migrations.RenameField(
            model_name='in_class_wise_merit_policy',
            old_name='roll_no',
            new_name='roll_no_priority',
        ),
        migrations.RenameField(
            model_name='in_class_wise_merit_policy',
            old_name='total_obtained_marks',
            new_name='total_obtained_marks_priority',
        ),
    ]
