# Generated by Django 4.1.5 on 2025-08-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0002_rename_is_average_gpa_in_class_wise_merit_policy_is_average_gpa_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_class_wise_merit_policy',
            name='is_bangla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='in_class_wise_merit_policy',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
    ]
