# Generated by Django 4.1.5 on 2025-08-29 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_setup', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups_setup', '0003_initial'),
        ('organizations', '0002_initial'),
        ('subject_setup', '0006_in_subjects_is_optional_wise_grade_cal'),
        ('policy_setup', '0003_in_class_wise_merit_policy_is_bangla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_subject_wise_merit_policy',
            fields=[
                ('subswisep_id', models.BigAutoField(default=1333014000000, editable=False, primary_key=True, serialize=False)),
                ('subject_priority', models.IntegerField(blank=True, help_text='Sorting priority for Subject', null=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1235700000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=155580000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2subswisepm', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2subswisepm', to='groups_setup.in_groups')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2subswisepm', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2subswisepm', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2subswisepm', to=settings.AUTH_USER_MODEL)),
                ('subjects_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subjects_id2subswisepm', to='subject_setup.in_subjects')),
            ],
        ),
    ]
