# Generated by Django 4.1.5 on 2025-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0004_in_subject_wise_merit_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_subject_wise_merit_policy',
            name='is_sub_groups',
            field=models.BooleanField(default=False),
        ),
    ]
