# Generated by Django 4.1.5 on 2025-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0005_in_subject_wise_merit_policy_is_sub_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_class_wise_merit_policy',
            name='is_fail_sub_count',
            field=models.BooleanField(default=False),
        ),
    ]
