# Generated by Django 4.1.5 on 2025-09-02 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section_setup', '0002_initial'),
        ('organizations', '0002_initial'),
        ('class_setup', '0003_initial'),
        ('policy_setup', '0006_in_class_wise_merit_policy_is_fail_sub_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='classSectionGroupingMap',
            fields=[
                ('clss_sec_map_id', models.BigAutoField(default=1110340000000, editable=False, primary_key=True, serialize=False)),
                ('is_order_by', models.IntegerField(blank=True, default=0, help_text='Sorting priority for Section', null=True)),
                ('is_group_no', models.IntegerField(blank=True, default=0, help_text='Group Number', null=True)),
                ('is_grouping_flag', models.BooleanField(default=False)),
                ('is_individual_flag', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1354600000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1365789000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2clss_sec_map', to='class_setup.in_class')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2clss_sec_map', to='organizations.organizationlst')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2clss_sec_map', to='section_setup.in_section')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2clss_sec_map', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2clss_sec_map', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
