# Generated by Django 4.1.5 on 2025-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0007_classsectiongroupingmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsectiongroupingmap',
            name='is_group_name',
            field=models.CharField(blank=True, help_text='Group Name', max_length=255, null=True),
        ),
    ]
