# Generated by Django 4.1.5 on 2025-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0008_classsectiongroupingmap_is_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_class_wise_merit_policy',
            name='is_gross_merit_position',
            field=models.BooleanField(default=False),
        ),
    ]
