# Generated by Django 4.1.5 on 2025-11-11 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section_setup', '0002_initial'),
        ('class_setup', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups_setup', '0003_initial'),
        ('organizations', '0002_initial'),
        ('policy_setup', '0009_in_class_wise_merit_policy_is_gross_merit_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='half_year_roll_section_change_policy',
            fields=[
                ('hyrscp_id', models.BigAutoField(default=1225240000000, editable=False, primary_key=True, serialize=False)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('from_roll', models.CharField(blank=True, max_length=20, null=True)),
                ('to_roll', models.CharField(blank=True, max_length=20, null=True)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1424600000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1572789000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2hyrscp_policy', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2hyrscp_policy', to='groups_setup.in_groups')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2hyrscp_policy', to='organizations.organizationlst')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2hyrscp_policy', to='section_setup.in_section')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2hyrscp_policy', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2hyrscp_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
