# Generated by Django 4.1.5 on 2025-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0010_half_year_roll_section_change_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='half_year_roll_section_change_policy',
            name='is_group_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='half_year_roll_section_change_policy',
            name='is_invd_flag',
            field=models.BooleanField(default=False),
        ),
    ]
