# Generated by Django 4.1.5 on 2025-11-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_setup', '0011_half_year_roll_section_change_policy_is_group_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='half_year_roll_section_change_policy',
            name='group_serials',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='half_year_roll_section_change_policy',
            name='hyrscp_year',
            field=models.IntegerField(default=2025, editable=False),
        ),
    ]
