# Generated by Django 4.1.5 on 2025-11-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_setup', '0002_initial'),
        ('policy_setup', '0012_half_year_roll_section_change_policy_group_serials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='half_year_roll_section_change_policy',
            name='shift_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_id2hyrscp_policy', to='shift_setup.in_shifts'),
        ),
    ]
