# Generated by Django 4.1.5 on 2025-11-21 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class_setup', '0003_initial'),
        ('policy_setup', '0013_half_year_roll_section_change_policy_shift_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='annual_exam_percentance_policy',
            fields=[
                ('aexperpo_id', models.BigAutoField(default=1554691000000, editable=False, primary_key=True, serialize=False)),
                ('aexperpo_year', models.IntegerField(default=2025, editable=False)),
                ('half_yearly_per', models.IntegerField(blank=True, null=True)),
                ('annual_per', models.IntegerField(blank=True, null=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1555780200000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1558890000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2aexperpolicy', to='class_setup.in_class')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2aexperpolicy', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2aexperpolicy', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2aexperpolicy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
