# Generated by Django 4.1.5 on 2025-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_return_receive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual_return_receive',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='manual_return_receive',
            name='manu_ret_rec_id',
            field=models.BigAutoField(db_index=True, default=9909099100000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual_return_receive',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='manual_return_receive',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='manual_return_receive',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='manual_return_receivedtl',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='manual_return_receivedtl',
            name='manu_ret_rec_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='manual_return_receivedtl',
            name='manu_ret_rec_dtl_id',
            field=models.BigAutoField(db_index=True, default=8008588000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual_return_receivedtl',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='manual_return_receivedtl',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='manual_return_receive',
            index=models.Index(fields=['id_org', 'branch_id', 'reg_id', 'transaction_date', 'is_approved'], name='manual_retu_id_org__0c99eb_idx'),
        ),
        migrations.AddIndex(
            model_name='manual_return_receive',
            index=models.Index(fields=['manu_ret_rec_no'], name='manual_retu_manu_re_76f8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='manual_return_receivedtl',
            index=models.Index(fields=['manu_ret_rec_id', 'reg_id', 'manu_ret_rec_date', 'is_approved'], name='manual_retu_manu_re_ec859d_idx'),
        ),
        migrations.AddIndex(
            model_name='manual_return_receivedtl',
            index=models.Index(fields=['item_id'], name='manual_retu_item_id_3d3f79_idx'),
        ),
        migrations.AddIndex(
            model_name='manual_return_receivedtl',
            index=models.Index(fields=['store_id'], name='manual_retu_store_i_5e2de9_idx'),
        ),
    ]
