# Generated by Django 4.1.5 on 2026-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner_list',
            fields=[
                ('banner_id', models.BigAutoField(default=1300000000001, editable=False, primary_key=True, serialize=False)),
                ('title_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_text', models.CharField(blank=True, max_length=150, null=True)),
                ('startup_price', models.CharField(blank=True, max_length=20, null=True)),
                ('banner_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='banner')),
                ('is_publist', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1102000010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1203000020000, editable=False, null=True)),
            ],
        ),
    ]
