# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift_setup', '0001_initial'),
        ('section_setup', '0001_initial'),
        ('groups_setup', '0002_initial'),
        ('class_setup', '0002_initial'),
        ('module_setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='others_access_list',
            fields=[
                ('other_acc_id', models.BigAutoField(default=3000000000010, editable=False, primary_key=True, serialize=False)),
                ('is_defaults', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=2300000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=103330000000, editable=False, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_id2others_access', to='class_setup.in_class')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups_id2others_access', to='groups_setup.in_groups')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_id2others_access', to='section_setup.in_section')),
                ('shifts_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shifts_id2others_access', to='shift_setup.in_shifts')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2others_access', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2others_access', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2others_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='lookup_values',
            fields=[
                ('lookup_id', models.BigAutoField(default=1000000001, editable=False, primary_key=True, serialize=False)),
                ('identify_code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1100100010000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1200200020000, editable=False, null=True)),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2lookup_values', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2lookup_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='access_list',
            fields=[
                ('access_id', models.BigAutoField(default=20000000001, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=2000000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=101110000000, editable=False, null=True)),
                ('feature_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feature_id2access_list', to='module_setup.feature_list')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2access_list', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2access_list', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id2access_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
