# Generated by Django 4.1.5 on 2025-06-16 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0004_organizationlst_is_start_up'),
        ('user_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceChargePayment',
            fields=[
                ('service_id', models.BigAutoField(default=1955500008000, editable=False, primary_key=True, serialize=False)),
                ('creater_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('service_month', models.CharField(blank=True, max_length=20, null=True)),
                ('service_year', models.CharField(blank=True, max_length=30, null=True)),
                ('service_amt', models.IntegerField(blank=True, null=True)),
                ('service_payment', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1672000000800, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=1789000000900, editable=False, null=True)),
                ('branch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch_id2service', to='organizations.branchslist')),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2service', to='organizations.organizationlst')),
                ('ss_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_creator2service', to=settings.AUTH_USER_MODEL)),
                ('ss_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ss_modifier2service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
