# Generated by Django 4.1.5 on 2025-07-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setup', '0002_others_access_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='others_access_list',
            old_name='is_defauls',
            new_name='is_defaults',
        ),
    ]
