# Generated by Django 4.1.5 on 2025-06-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setup', '0002_servicechargepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='servicechargepayment',
            name='transaction_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
