# Generated by Django 4.1.5 on 2025-06-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setup', '0004_servicechargepayment_is_passing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicechargepayment',
            old_name='transaction_details',
            new_name='payment_trans_id',
        ),
    ]
