# Generated by Django 4.1.5 on 2026-09-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(help_text='Example: Morsheda & Saquib', max_length=150)),
                ('message', models.TextField(help_text='Client er testimonial text')),
                ('image', models.ImageField(blank=True, help_text='Client er round avatar image (optional)', null=True, upload_to='testimonials/')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved na hoile website a show hobe na')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
