# Generated by Django 4.1.5 on 2025-04-27 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_setup', '0002_initial'),
        ('item_setup', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='default_store',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='store_id2items', to='store_setup.store'),
        ),
    ]
