# Generated by Django 4.1.5 on 2025-08-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_section',
            fields=[
                ('section_id', models.BigAutoField(default=123030000000, editable=False, primary_key=True, serialize=False)),
                ('section_no', models.CharField(blank=True, max_length=50, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_english', models.BooleanField(default=False)),
                ('is_bangla', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('ss_created_on', models.DateTimeField(auto_now_add=True)),
                ('ss_created_session', models.BigIntegerField(blank=True, default=1232000000000, editable=False, null=True)),
                ('ss_modified_on', models.DateTimeField(auto_now=True)),
                ('ss_modified_session', models.BigIntegerField(blank=True, default=112360000000, editable=False, null=True)),
                ('org_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_id2in_section', to='organizations.organizationlst')),
            ],
        ),
    ]
