# Generated by Django 4.1.5 on 2026-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
