# Generated by Django 4.1.5 on 2026-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_feed', '0002_facebookpost_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100)),
                ('access_token', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='facebook_images/'),
        ),
    ]
