# Generated by Django 4.1.5 on 2025-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_purchase', '0005_alter_local_purchasedtl_lp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_purchase',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='is_cash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='is_credit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='lp_id',
            field=models.BigAutoField(db_index=True, default=2202022100000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='lp_no',
            field=models.CharField(db_index=True, editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='local_purchase',
            name='transaction_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='local_purchasedtl',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='local_purchasedtl',
            name='lp_dtl_id',
            field=models.BigAutoField(db_index=True, default=1005555000000, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='local_purchasedtl',
            name='lp_rec_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='local_purchasedtl',
            name='ss_created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='local_purchasedtl',
            name='ss_modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='local_purchase',
            index=models.Index(fields=['id_org', 'branch_id', 'reg_id', 'transaction_date', 'is_approved'], name='local_purch_id_org__5c40cb_idx'),
        ),
        migrations.AddIndex(
            model_name='local_purchase',
            index=models.Index(fields=['lp_no'], name='local_purch_lp_no_3e7d21_idx'),
        ),
        migrations.AddIndex(
            model_name='local_purchasedtl',
            index=models.Index(fields=['lp_id', 'reg_id', 'lp_rec_date', 'is_approved'], name='local_purch_lp_id_i_890b60_idx'),
        ),
        migrations.AddIndex(
            model_name='local_purchasedtl',
            index=models.Index(fields=['item_id'], name='local_purch_item_id_9ded36_idx'),
        ),
        migrations.AddIndex(
            model_name='local_purchasedtl',
            index=models.Index(fields=['store_id'], name='local_purch_store_i_588659_idx'),
        ),
    ]
